# Site settings
title: Alexandros Ritas
description: Just a theme.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alexandros Ritas
user_description: I'm a Data Engineer from Greece, always searching for the next challenge.
user_title: Data Engineer
email: alexandrosritas@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: 
# facebook_username: 
linkedin_username: https://www.linkedin.com/in/alexritas/
github_username:  https://github.com/alexritas
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

